/**
 * Wishlist Model - User Product Wishlist
 * 
 * This model represents items that users have saved to their wishlist.
 * Users can save products they're interested in for future purchase.
 * 
 * Database Table: wishlists
 * 
 * Relationships:
 * - Many-to-One with User (Wishlist belongs to User)
 * - Many-to-One with Flower (Wishlist references Flower)
 * 
 * Business Rules:
 * - Users can add/remove items from their wishlist
 * - Each user can only have one entry per product in wishlist
 * - Wishlist items are preserved even if product is discontinued
 * - Users can share their wishlist (future feature)
 * 
 * @author Flower Shop Team
 * @version 1.0.0
 */

import { DataTypes } from 'sequelize';
import sequelize from '../config/sequelize.js';

/**
 * Wishlist Model Definition
 * 
 * Defines the structure for user wishlist items.
 * Simple many-to-many relationship between users and flowers.
 */
const Wishlist = sequelize.define('Wishlist', {
    /**
     * Primary Key - Auto-incrementing ID
     * Automatically generated by Sequelize
     */
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        comment: 'Unique identifier for each wishlist item'
    },

    /**
     * User ID - Foreign key to users table
     */
    userId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
            model: 'users',
            key: 'id'
        },
        onDelete: 'CASCADE',
        comment: 'ID of the user who owns this wishlist item'
    },

    /**
     * Flower ID - Foreign key to flowers table
     */
    flowerId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
            model: 'flowers',
            key: 'id'
        },
        onDelete: 'CASCADE',
        comment: 'ID of the flower product in the wishlist'
    },

    /**
     * Notes - Optional notes about why user wants this item
     */
    notes: {
        type: DataTypes.TEXT,
        allowNull: true,
        validate: {
            len: {
                args: [0, 500],
                msg: 'Notes cannot exceed 500 characters'
            }
        },
        comment: 'Optional notes about this wishlist item'
    }
}, {
    // Table configuration
    tableName: 'wishlists',
    timestamps: true, // Enable automatic createdAt and updatedAt
});

export default Wishlist;